import assert from "node:assert/strict";
import {setImmediate as tick,setTimeout as pause} from "node:timers/promises";
import {test} from "node:test";
import {PlayerEngine,connectMedia,orderedSources} from "../lib/player";
import {defaults,recordSuccess,recordFailure} from "../lib/local-state";
let manifest='#EXTM3U\n#EXT-X-TARGETDURATION:0\n#EXTINF:6,\nsegment.ts';
let sequence=0;const originalTimeout=globalThis.setTimeout;globalThis.setTimeout=((fn:any,delay:any,...args:any[])=>originalTimeout(fn,delay===1000?0:delay,...args)) as typeof setTimeout;
Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>new Response(manifest+'\n#EXT-X-MEDIA-SEQUENCE:'+ ++sequence+'\n#EXTINF:6,\nseg-'+sequence+'.ts',{headers:{'Content-Type':'application/vnd.apple.mpegurl'}})});
async function waitFor(check:()=>boolean){for(let i=0;i<100&&!check();i++)await pause(5);assert.ok(check());}
let online=true;const page={visibilityState:'visible'};
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{get onLine(){return online;}}});Object.defineProperty(globalThis,'document',{configurable:true,value:page});
class Video extends EventTarget{src='';currentTime=0;videoWidth=1920;videoHeight=1080;readyState=0;paused=true;ended=false;muted=true;denied=false;canPlayType(){return 'probably';}play(){if(this.denied)return Promise.reject(new DOMException('gesture','NotAllowedError'));this.paused=false;this.readyState=3;this.dispatchEvent(new Event('playing'));return Promise.resolve();}pause(){this.paused=true;this.dispatchEvent(new Event('pause'));}load(){}removeAttribute(){this.src='';this.currentTime=0;this.readyState=0;}advance(t:number){this.currentTime=t;this.dispatchEvent(new Event('timeupdate'));}}
const channel={id:'test',name:'test',title:'test',group:'test',sources:[{id:'https://a.example/live.m3u8',url:'https://a.example/live.m3u8'},{id:'https://b.example/live.m3u8',url:'https://b.example/live.m3u8'}]};
test('failed first source switches automatically and verifies actual video progress',async()=>{const v=new Video(),p=defaults();const engine=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{});engine.play(channel);await waitFor(()=>!!v.src);assert.equal(v.src,channel.sources[0].url);assert.equal(engine.current.status,'connecting');v.dispatchEvent(new Event('error'));await waitFor(()=>!!v.src);assert.equal(v.src,channel.sources[1].url);assert.equal(p.health[channel.sources[0].id].failures,1);v.advance(1);assert.equal(engine.current.status,'connecting');v.advance(3.1);await waitFor(()=>p.recent[0]==='test');assert.equal(engine.current.status,'playing');assert.equal(p.recent[0],'test');engine.dispose();});
test('paused, offline and hidden playback errors do not blacklist or switch',async()=>{const v=new Video(),p=defaults();const e=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{});e.play(channel);await waitFor(()=>!!v.src);v.advance(1);v.advance(4);await waitFor(()=>!!p.health[channel.sources[0].id]?.verifiedLive);v.pause();v.dispatchEvent(new Event('error'));assert.equal(e.current.status,'paused');assert.equal(p.health[channel.sources[0].id].failures,0);e.resume();online=false;v.dispatchEvent(new Event('error'));online=true;page.visibilityState='hidden';v.dispatchEvent(new Event('error'));page.visibilityState='visible';assert.equal(p.health[channel.sources[0].id].failures,0);e.dispose();});
test('success cache has priority; cooling sources are skipped',()=>{const p=defaults();recordSuccess(p,channel.sources[1].id);assert.equal(orderedSources(channel,p)[0].id,channel.sources[1].id);recordFailure(p,channel.sources[1].id);assert.equal(orderedSources(channel,p)[0].id,channel.sources[0].id);});
test('autoplay denial is a gesture state and does not become source failure',async()=>{const v=new Video();v.denied=true;let blocked=0,failed=0;const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>{},failure:()=>failed++,blocked:()=>blocked++});await waitFor(()=>blocked===1);assert.equal(blocked,1);assert.equal(failed,0);c.stop();});
test('audio-only progress is not video verification; cancellation is not failure',()=>{const v=new Video();v.videoWidth=0;let verified=0,failed=0;const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,failure:()=>failed++,blocked:()=>{}});v.advance(1);v.advance(5);assert.equal(verified,0);c.stop();v.dispatchEvent(new Event('error'));assert.equal(failed,0);});
test('auto-switch off stops after interruption of a verified stream',async()=>{const v=new Video(),p=defaults();const e=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{});e.auto=false;e.play(channel);await waitFor(()=>!!v.src);v.advance(1);v.advance(4);await waitFor(()=>!!p.health[channel.sources[0].id]?.verifiedLive);v.dispatchEvent(new Event('error'));assert.equal(e.current.status,'stopped');assert.equal(e.attempted.size,1);e.dispose();});

test('ended HLS playlists reject instead of reporting live playback',async()=>{const {playlistType}=await import('../lib/player');assert.equal(playlistType(manifest),'live');assert.equal(playlistType(manifest+'\n#EXT-X-ENDLIST'),'vod');const v=new Video();let rejected=0;manifest+='\n#EXT-X-ENDLIST';const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>assert.fail('VOD verified'),failure:()=>rejected++,blocked:()=>{}});await tick();assert.equal(rejected,1);c.stop();manifest=manifest.replace('\n#EXT-X-ENDLIST','');});

test('only advancing live playlists pass; static and ended lists fail',async()=>{const {livePlaylistAdvanced}=await import('../lib/player');const a='#EXTM3U\n#EXT-X-MEDIA-SEQUENCE:1\n#EXTINF:6,\n1.ts';const b=a.replace('SEQUENCE:1','SEQUENCE:2').replace('1.ts','2.ts');assert.equal(livePlaylistAdvanced(a,a),false);assert.equal(livePlaylistAdvanced(a,b),true);assert.equal(livePlaylistAdvanced(a,b+'\n#EXT-X-ENDLIST'),false);});

test('manual selection tries the chosen cooling source first and reports ping before video verification',async()=>{const v=new Video(),p=defaults();recordSuccess(p,channel.sources[0].id);recordFailure(p,channel.sources[1].id);const events:string[]=[];const e=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{},(_id,r)=>events.push(r.status));e.play(channel,false,channel.sources[1].id);assert.equal(events[0],'pinging');await waitFor(()=>!!v.src);assert.equal(v.src,channel.sources[1].url);await waitFor(()=>events.includes('checking'));assert.equal(events[1],'checking');v.advance(1);v.advance(4);await waitFor(()=>events.at(-1)==='available');assert.equal(events.at(-1),'available');e.dispose();});
test('failed connectivity request stops before manifest and playback; HTTP status remains visible',async()=>{const old=globalThis.fetch;let calls=0,reason='',connected=0;Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>{calls++;return new Response('',{status:503});}});const v=new Video();v.canPlayType=()=>'';const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>assert.fail(),failure:r=>reason=r||'',reachable:()=>connected++,blocked:()=>{}});try{await tick();assert.equal(calls,1);assert.match(reason,/HTTP 503/);assert.equal(connected,0);assert.equal(v.src,'');assert.equal(v.paused,true);}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}});
test('cross-origin or network rejection is not labeled as a dead upstream',async()=>{const old=globalThis.fetch;Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>{throw new TypeError('Failed to fetch');}});let reason='';const v=new Video();v.canPlayType=()=>'';const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>assert.fail(),failure:r=>reason=r||'',blocked:()=>{}});try{await tick();assert.match(reason,/跨域.*无法确认/);}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}});
test('selected-channel scan processes every source once, excludes the main player, and classifies unsupported sources',async()=>{const {initialSourceChecks,nextSourceToCheck}=await import('../lib/source-checks');const all={...channel,sources:[...channel.sources,{id:'https://c.example/live.m3u8',url:'https://c.example/live.m3u8'},{id:'http://old.example/live',url:'http://old.example/live'},{id:'https://vod.example/movie.mp4',url:'https://vod.example/movie.mp4'}]};const checks=initialSourceChecks(all);assert.equal(checks[all.sources[3].id].status,'waiting');assert.equal(checks[all.sources[4].id].status,'unsupported');const selected=all.sources[0].id;checks[selected]={status:'available'};let source=nextSourceToCheck(all,checks,selected);assert.equal(source?.id,all.sources[1].id);checks[source!.id]={status:'failed'};source=nextSourceToCheck(all,checks,selected);assert.equal(source?.id,all.sources[2].id);checks[source!.id]={status:'available'};source=nextSourceToCheck(all,checks,selected);assert.equal(source?.id,all.sources[3].id);checks[source!.id]={status:'available'};assert.equal(nextSourceToCheck(all,checks,selected),undefined);assert.equal(initialSourceChecks(all)[selected].status,'waiting');});

test('HTTP source uses same-origin relay while health retains original source identity',async()=>{const v=new Video(),p=defaults();const url='http://42.94.210.135:7788/641886773';const c={...channel,sources:[{id:url,url}]};const e=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{});e.play(c);await waitFor(()=>!!v.src);assert.equal(v.src,'/api/stream?source='+encodeURIComponent(url));v.advance(1);v.advance(4);await waitFor(()=>!!p.health[url]?.verifiedLive);assert.equal(e.current.source,url);assert.ok(p.health[url].verifiedLive);e.dispose();});

test('hide-failed filter retains unknown, pending, testing, blocked and unsupported sources',async()=>{const {sourceVisible}=await import('../lib/source-checks');assert.equal(sourceVisible({status:'failed'},true),false);assert.equal(sourceVisible({status:'failed'},false),true);for(const status of ['waiting','pinging','checking','available','blocked','unsupported'] as const)assert.equal(sourceVisible({status},true),true);assert.equal(sourceVisible(undefined,true),true);});

test('relayed source taking nine seconds to connect is not rejected by the direct-source six-second budget',async()=>{const oldFetch=globalThis.fetch,oldTimer=globalThis.setTimeout;let calls=0,failed=0;globalThis.setTimeout=((fn:any,delay:number,...args:any[])=>originalTimeout(fn,delay===1000?0:delay/1000,...args)) as typeof setTimeout;Object.defineProperty(globalThis,'fetch',{configurable:true,value:async(_url:unknown,init:RequestInit)=>{await new Promise(r=>originalTimeout(r,9));if(init.signal?.aborted)throw new DOMException('Aborted','AbortError');return new Response('#EXTM3U\n#EXT-X-TARGETDURATION:0\n#EXT-X-MEDIA-SEQUENCE:'+ ++calls+'\n#EXTINF:6,\nseg-'+calls+'.ts');}});const v=new Video();const c=connectMedia(v as unknown as HTMLVideoElement,'http://42.94.210.135:7788/641886773',{verified:()=>{},failure:()=>failed++,blocked:()=>{}});try{await waitFor(()=>!!v.src);assert.equal(failed,0);}finally{c.stop();globalThis.setTimeout=oldTimer;Object.defineProperty(globalThis,'fetch',{configurable:true,value:oldFetch});}});

test('per-channel last watched source wins without expiry; probes do not replace it and removed sources are ignored',async()=>{const v=new Video(),p=defaults(),e=new PlayerEngine(v as unknown as HTMLVideoElement,p,()=>{},()=>{},()=>{});e.play(channel,false,channel.sources[1].id);await waitFor(()=>!!v.src);v.advance(1);v.advance(4);await waitFor(()=>!!p.lastPlayedSources.test);assert.equal(p.lastPlayedSources.test,channel.sources[1].id);assert.ok(p.lastPlayedAt.test>0);const watchedAt=p.lastPlayedAt.test;e.dispose();p.health[channel.sources[1].id].okAt=Date.now()-3*86400_000;recordSuccess(p,channel.sources[0].id);assert.equal(p.lastPlayedAt.test,watchedAt);recordFailure(p,channel.sources[1].id);assert.equal(orderedSources(channel,p)[0].id,channel.sources[0].id);assert.equal(orderedSources(channel,p,new Set([channel.sources[1].id]))[0].id,channel.sources[0].id);assert.equal(orderedSources({...channel,sources:[channel.sources[0]]},p)[0].id,channel.sources[0].id);assert.equal(p.lastPlayedSources.test,channel.sources[1].id);assert.equal(orderedSources({...channel,id:'another-channel'},p)[0].id,channel.sources[0].id);});

test('current-device instability overrides last-played preference for automatic attempts',()=>{const p=defaults(),now=Date.now();const shared={[channel.sources[0].id]:{okAt:0,failedAt:now},[channel.sources[1].id]:{okAt:now,failedAt:0}};assert.equal(orderedSources(channel,p,new Set(),shared)[0].id,channel.sources[1].id);p.lastPlayedSources[channel.id]=channel.sources[0].id;assert.equal(orderedSources(channel,p,new Set(),shared)[0].id,channel.sources[1].id);});
test('switching during shared-health loading does not start the abandoned channel',async()=>{const v=new Video(),e=new PlayerEngine(v as unknown as HTMLVideoElement,defaults(),()=>{},()=>{},()=>{});let release:(value:{})=>void=()=>{};e.loadShared=()=>new Promise(resolve=>{release=resolve;});e.play(channel);const oldRelease=release;const second={...channel,id:'second',sources:[channel.sources[1]]};e.play(second);oldRelease({});await tick();assert.equal(v.src,'');release({});await waitFor(()=>!!v.src);assert.equal(v.src,channel.sources[1].url);e.dispose();});


test('native HLS starts despite CORS fetch failure and verifies via authorized relay',async()=>{
 const old=globalThis.fetch;let seq=0;const requests:string[]=[];let verified=0,failed=0;
 Object.defineProperty(globalThis,'fetch',{configurable:true,value:async(url:string)=>{requests.push(url);if(url.startsWith('https:'))throw new TypeError('CORS');return new Response('#EXTM3U\n#EXT-X-TARGETDURATION:0\n#EXT-X-MEDIA-SEQUENCE:'+ ++seq+'\n#EXTINF:6,\n'+seq+'.ts');}});
 const v=new Video();const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,failure:()=>failed++,blocked:()=>{}});
 try{assert.equal(v.src,channel.sources[0].url);assert.equal(v.paused,false);v.advance(1);v.advance(4);await waitFor(()=>verified===1);assert.equal(failed,0);assert.ok(requests.some(url=>url.startsWith('/api/stream?source=')));}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}
});
test('native frames stay playable when manifests cannot be inspected, without a false success or failure report',async()=>{
 const old=globalThis.fetch;Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>{throw new TypeError('CORS/relay unavailable');}});
 const v=new Video();let verified=0,failed=0,unconfirmed=0;const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,unconfirmed:()=>unconfirmed++,failure:()=>failed++,blocked:()=>{}});
 try{v.advance(1);v.advance(4);await waitFor(()=>unconfirmed===1);assert.equal(verified,0);assert.equal(failed,0);assert.equal(v.paused,false);}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}
});
test('mobile and iPad desktop UA disable hidden playback probes; desktop keeps them',async()=>{
 const {deviceClass,supportsBackgroundProbe}=await import('../lib/device-class');
 for(const nav of [{userAgent:'iPhone CriOS Safari'},{userAgent:'Android Chrome Mobile'},{userAgent:'iPhone MicroMessenger'},{userAgent:'Macintosh',platform:'MacIntel',maxTouchPoints:5}])assert.equal(supportsBackgroundProbe(deviceClass(nav)),false);
 assert.equal(supportsBackgroundProbe(deviceClass({userAgent:'Windows Chrome',maxTouchPoints:1})),true);
});


test('mobile failure fallback is delayed, single-player, and suspended while hidden',async()=>{
 const oldTimer=globalThis.setTimeout;const ua=Object.getOwnPropertyDescriptor(navigator,'userAgent');
 Object.defineProperty(navigator,'userAgent',{configurable:true,value:'Android Chrome Mobile'});
 const queued:Array<()=>void>=[];globalThis.setTimeout=((fn:any,ms:number,...args:any[])=>ms===1500?(queued.push(fn),0):oldTimer(fn,ms,...args)) as typeof setTimeout;
 const v=new Video(),e=new PlayerEngine(v as unknown as HTMLVideoElement,defaults(),()=>{},()=>{},()=>{});
 try{e.play(channel);assert.equal(e.attempted.size,1);v.dispatchEvent(new Event('error'));assert.equal(v.src,'');assert.equal(e.attempted.size,1);assert.equal(queued.length,1);page.visibilityState='hidden';queued.shift()!();assert.equal(v.src,'');assert.equal(e.attempted.size,1);page.visibilityState='visible';queued.shift()!();assert.equal(e.attempted.size,2);assert.equal(v.src,channel.sources[1].url);}finally{e.dispose();page.visibilityState='visible';globalThis.setTimeout=oldTimer;if(ua)Object.defineProperty(navigator,'userAgent',ua);else delete (navigator as any).userAgent;}
});

test('desktop native probe waits for live inspection before announcing verified frames',async()=>{
 const v=new Video();let verified=0,unconfirmed=0;
 const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,unconfirmed:()=>unconfirmed++,failure:()=>assert.fail('unexpected failure'),blocked:()=>{}},true);
 try{v.advance(1);v.advance(4);assert.equal(unconfirmed,0);await waitFor(()=>verified===1);assert.equal(unconfirmed,0);}finally{c.stop();}
});

test('native inspection tolerates an unchanged sample and verifies a later playlist update',async()=>{
 const old=globalThis.fetch;let requests=0,failed=0,verified=0;
 Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>{requests++;return new Response(manifest+(requests>=3?'\n#EXT-X-MEDIA-SEQUENCE:2\n#EXTINF:6,\nnew.ts':''));}});
 const v=new Video(),c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,failure:()=>failed++,blocked:()=>{}});
 try{v.advance(1);v.advance(4);await waitFor(()=>verified===1);assert.equal(requests,3);assert.equal(failed,0);}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}
});
test('a fixed native playlist never becomes available despite moving video frames',async()=>{
 const old=globalThis.fetch;let requests=0,reason='',verified=0;
 Object.defineProperty(globalThis,'fetch',{configurable:true,value:async()=>{requests++;return new Response(manifest);}});
 const v=new Video(),c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>verified++,failure:r=>reason=r||'',blocked:()=>{}});
 try{v.advance(1);v.advance(24);await waitFor(()=>!!reason);assert.equal(requests,4);assert.equal(verified,0);assert.match(reason,/连续未更新/);}finally{c.stop();Object.defineProperty(globalThis,'fetch',{configurable:true,value:old});}
});
test('native decode failures include a diagnostic code',()=>{
 const v=new Video();Object.defineProperty(v,'error',{value:{code:3}});let reason='';
 const c=connectMedia(v as unknown as HTMLVideoElement,channel.sources[0].url,{verified:()=>{},failure:r=>reason=r||'',blocked:()=>{}});
 try{v.dispatchEvent(new Event('error'));assert.match(reason,/解码.*3/);}finally{c.stop();}
});
