import assert from 'node:assert/strict';
import {test} from 'node:test';
import {publicUrl,signingKey,signedPath,verifyTicket,rewritePlaylist,fetchRedirects,readPlaylist,assetHeaders,TICKET_LIFETIME} from '../lib/stream-relay';
import {livePlaylistAdvanced} from '../lib/player';
const base='http://cdn.example:8080/live/index.m3u8?session=a';
const now=Math.floor(Date.now()/1000),expiry=now+TICKET_LIFETIME;
const key=await signingKey('test-only-random-fixture');
test('relay tickets bind URL, kind and expiry; tampering and expired links fail',async()=>{const path=await signedPath(base,expiry,'playlist',key);const p=new URL(path,'https://site.example').searchParams;assert.ok(await verifyTicket(p.get('u')!,expiry,'playlist',p.get('s')!,key,now));assert.equal(await verifyTicket(base,expiry,'asset',p.get('s')!,key,now),false);assert.equal(await verifyTicket(base+'x',expiry,'playlist',p.get('s')!,key,now),false);assert.equal(await verifyTicket(base,expiry,'playlist',p.get('s')!,key,expiry+1),false);});
test('private, local, encoded-IP and non-HTTP destinations reject at every hop',()=>{for(const url of ['http://127.0.0.1/','http://2130706433/','http://0x7f000001/','http://169.254.169.254/','http://10.0.0.1/','http://192.168.1.1/','http://100.64.0.1/','http://[::1]/','http://[::ffff:127.0.0.1]/','http://localhost./','http://metadata.internal/','file:///a','http://user:pass@example.com/'])assert.throws(()=>publicUrl(url));assert.equal(publicUrl('http://42.94.210.135:7788/641886773').port,'7788');});
test('master playlists rewrite variants and audio URLs against the final redirect URL',async()=>{const input='#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,URI="audio/list.m3u8?x=1"\n#EXT-X-STREAM-INF:BANDWIDTH=1200\n01.m3u8?token=z';const output=await rewritePlaylist(input,base,expiry,key);const urls=[...output.matchAll(/(?:URI="|\n)(\/api\/stream[^"\n]*)/g)].map(m=>new URL(m[1],'https://site.example').searchParams);assert.equal(urls.length,2);assert.ok(urls.every(p=>p.get('k')==='playlist'));assert.equal(urls[0].get('u'),'http://cdn.example:8080/live/audio/list.m3u8?x=1');assert.equal(urls[1].get('u'),'http://cdn.example:8080/live/01.m3u8?token=z');});
test('media playlists rewrite keys, maps, parts and segments without changing byte ranges',async()=>{const input='#EXTM3U\n#EXT-X-MEDIA-SEQUENCE:10\n#EXT-X-KEY:METHOD=AES-128,URI="../key?id=1"\n#EXT-X-MAP:URI="init.mp4",BYTERANGE="100@0"\n#EXT-X-PART:DURATION=0.5,URI="part.m4s"\n#EXT-X-BYTERANGE:200@100\n#EXTINF:6,\nseg.ts?token=a';const output=await rewritePlaylist(input,base,expiry,key);assert.equal((output.match(/\/api\/stream\?/g)||[]).length,4);assert.match(output,/#EXT-X-BYTERANGE:200@100/);assert.match(output,/BYTERANGE="100@0"/);assert.ok(!output.includes('URI="../'));assert.match(output,/k=asset/);});
test('redirects preserve byte-range requests without forwarding cookies or authorization',async()=>{const calls:{url:string;headers:Headers}[]=[];const fetched=async(input:any,init:any)=>{calls.push({url:String(input),headers:new Headers(init.headers)});return calls.length===1?new Response(null,{status:302,headers:{Location:'http://cdn.example:8080/seg.ts'}}):new Response(new Uint8Array([1,2,3]),{status:206,headers:{'Content-Range':'bytes 2-4/9','Accept-Ranges':'bytes'}});};const result=await fetchRedirects('http://entry.example:7788/live',new Request('https://site.example/api/stream',{headers:{Range:'bytes=2-4',Cookie:'secret=x',Authorization:'Bearer private'}}),async u=>{publicUrl(u.href);},fetched as typeof fetch);assert.equal(result.url,'http://cdn.example:8080/seg.ts');assert.equal(result.response.status,206);assert.deepEqual([...new Uint8Array(await result.response.arrayBuffer())],[1,2,3]);for(const call of calls){assert.equal(call.headers.get('Range'),'bytes=2-4');assert.equal(call.headers.get('Cookie'),null);assert.equal(call.headers.get('Authorization'),null);}assert.equal(assetHeaders(result.response.headers).get('Content-Range'),'bytes 2-4/9');await assert.rejects(()=>fetchRedirects('http://entry.example/live',new Request('https://site.example'),async()=>{},(async()=>new Response(null,{status:302,headers:{Location:'http://127.0.0.1/'}})) as typeof fetch));});
test('playlist size is bounded and relay signature changes do not fake live advancement',async()=>{await assert.rejects(()=>readPlaylist(new Response('123456'),3));const input='#EXTM3U\n#EXT-X-MEDIA-SEQUENCE:1\n#EXTINF:6,\nseg.ts';const a=await rewritePlaylist(input,base,expiry,key),b=await rewritePlaylist(input,base,expiry-1,key);assert.equal(livePlaylistAdvanced(a,b),false);assert.equal(livePlaylistAdvanced(a,await rewritePlaylist(input.replace('seg.ts','seg2.ts'),base,expiry,key)),true);});

test('IP entry uses a verified DNS alias while relative redirect bases retain original URLs',async()=>{const {networkTarget,validateAddresses}=await import('../lib/stream-relay');const original='http://42.94.210.135:7788/live/index.m3u8';const target=networkTarget(publicUrl(original));assert.equal(target.url.href,'http://42-94-210-135.sslip.io:7788/live/index.m3u8');assert.equal(target.expectedAddress,'42.94.210.135');validateAddresses(['42.94.210.135'],target.expectedAddress);assert.throws(()=>validateAddresses(['8.8.8.8'],target.expectedAddress));assert.throws(()=>validateAddresses(['127.0.0.1']));assert.equal(networkTarget(publicUrl('https://42.94.210.135/live')).url.hostname,'42.94.210.135');const calls:string[]=[];const result=await fetchRedirects(original,new Request('https://site.example'),async(u,expected)=>{assert.equal(expected,'42.94.210.135');assert.equal(u.hostname,'42-94-210-135.sslip.io');},(async(url)=>{calls.push(String(url));return calls.length===1?new Response(null,{status:302,headers:{Location:'next.m3u8'}}):new Response('#EXTM3U');}) as typeof fetch);assert.equal(result.url,'http://42.94.210.135:7788/live/next.m3u8');assert.equal(calls[1],'http://42-94-210-135.sslip.io:7788/live/next.m3u8');});

test('relay reports the failing redirect hop and host without exposing query credentials',async()=>{let calls=0;await assert.rejects(()=>fetchRedirects('http://entry.example/live?token=private',new Request('https://site.example'),async()=>{},(async()=>{if(++calls===1)return new Response(null,{status:302,headers:{Location:'http://cdn.example/live?token=private'}});throw new DOMException('Timed out','TimeoutError');}) as typeof fetch),error=>{assert.match((error as Error).message,/第 2 跳：cdn.example/);assert.ok(!(error as Error).message.includes('private'));return true;});});
