"use client";
import { useEffect,useRef,useState } from "react";
import { flushSync } from "react-dom";
import { Radio,Search,Star,Play,Signal,ShieldCheck,RefreshCw,ArrowUpRight,Tv,History,LoaderCircle,Volume2,WifiOff } from "lucide-react";
import {SourceList} from "@/components/source-list";
import { Switch } from "@/components/ui/switch";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { Empty,EmptyDescription } from "@/components/ui/empty";
import { useTV } from "@/lib/use-tv";
import {channelListPage,compareChannelSourceCounts,compareLastPlayed} from "@/lib/channel-list";
import {CATEGORIES,compareCategoryNames} from "@/lib/channel-category";
import {browserSources,channelDisplayName} from "@/lib/catalog";
import type { Channel } from "@/lib/catalog";
const statusText={idle:"准备连接",connecting:"正在自动连接…",playing:"正在播放",paused:"已暂停",blocked:"点击即可播放",recovering:"正在自动恢复…",unavailable:"当前网络暂无可播放线路",offline:"网络已断开",stopped:"播放已中断"};
const showCatalogRefresh=process.env.NEXT_PUBLIC_SHOW_CATALOG_REFRESH==="true";
const featured=["CCTV5+","CCTV13","CCTV4","CCTV9"];
type WebTool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown};
type ModelContext={registerTool:(tool:WebTool,options:{signal:AbortSignal})=>void|Promise<void>};
export default function Home(){
 const tv=useTV();const [query,setQuery]=useState("");const [tab,setTab]=useState("all");const [visibleCount,setVisibleCount]=useState(80);const [expanded,setExpanded]=useState(false);const [muted,setMuted]=useState(true);const tvRef=useRef(tv);tvRef.current=tv;
 useEffect(()=>{
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifetime=new AbortController();
  const tools:WebTool[]=[{name:"search_channels",description:"Search the current television catalog. Availability is local to this browser, and a catalog entry does not imply that it plays.",inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=="object"||typeof (input as {query?:unknown}).query!=="string")throw new Error("query must be a string");const query=(input as {query:string}).query.toLowerCase();return tvRef.current.catalog.channels.filter(c=>(c.name+c.title).toLowerCase().includes(query)).slice(0,30).map(c=>({id:c.id,title:c.title,group:c.group,unavailable:tvRef.current.isUnavailable(c)}));}},{name:"start_channel_playback",description:"Select a television channel and start automatic connection in the visible player. This starts an attempt, not a guarantee of playback.",inputSchema:{type:"object",properties:{channelId:{type:"string"}},required:["channelId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=="object"||typeof (input as {channelId?:unknown}).channelId!=="string")throw new Error("channelId must be a string");const id=(input as {channelId:string}).channelId;if(!tvRef.current.ready||!tvRef.current.catalog.channels.some(c=>c.id===id))throw new Error("Unknown channel or player not ready");flushSync(()=>tvRef.current.selectChannel(id));return {selectedChannel:tvRef.current.selected?.id,status:tvRef.current.playback.status};}}];
  for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}
  return()=>lifetime.abort();
 },[]);
 useEffect(()=>{setVisibleCount(80);setExpanded(false);},[query,tab,tv.category]);
 const selected=tv.selected??{id:"",name:"选择频道",title:"",group:"",sources:[]};const state=tv.playback.status;const busy=state==="connecting"||state==="recovering";const playing=state==="playing";const hasVideo=!!tv.playback.source;const starred=tv.prefs.favorites.includes(selected.id);
 const categories=CATEGORIES;const catalogNotice=tv.notice.includes("目录")?tv.notice:"";
 const channelSignal=(c:Channel)=>{
  if(!browserSources(c).length)return "restricted";
  if(c.id===selected.id){if(state==="offline")return "offline";if(busy)return "checking";if(state==="unavailable"||state==="stopped")return "unavailable";if(state==="playing"||state==="paused")return tv.playback.streamType==="live"?"ready":"pending";}
  if(tv.isUnavailable(c))return "unavailable";
  if(tv.lastSuccess(c))return "ready";
  if(tv.othersPlayable(c))return "shared";
  if(tv.probingId===c.id)return "checking";
  return tv.lastSuccess(c)?"stale":"pending";
 };
 const signalLabels={shared:"他人近期可播",restricted:"网页直连受限",offline:"网络已断开",checking:"正在验证",unavailable:"暂不可播",ready:"本机近期可播",stale:"曾经播放，待复验",pending:"待本机验证"};
 const channelStatus=(c:Channel)=>signalLabels[channelSignal(c)];
 const filtered=tv.catalog.channels.filter(c=>{
  const matches=(c.name+c.title).toLowerCase().includes(query.trim().toLowerCase());
  if(!matches||tv.prefs.hideFailed&&tv.hasFailed(c))return false;if(tab==="favorites")return tv.prefs.favorites.includes(c.id);if(tab==="recent")return tv.prefs.recent.includes(c.id);
  if(tab==="available")return tv.lastSuccess(c)>0;
  if(tab==="shared")return tv.othersPlayable(c);
  if(query)return true;return(tv.category==="全部"||c.group===tv.category);
 }).sort((a,b)=>tab==="recent"?tv.prefs.recent.indexOf(a.id)-tv.prefs.recent.indexOf(b.id):tab==="available"?compareLastPlayed(a,b,tv.prefs.lastPlayedAt,tv.prefs.recent):(tab==="shared"||tab==="all"&&tv.category==="全部")&&!query.trim()?compareChannelSourceCounts(a,b):compareCategoryNames(a.name,b.name,tab==="all"&&!query?tv.category:"全部"));
 const channelPage=channelListPage(filtered,!!query.trim()||tab==="shared",expanded,visibleCount);
 const suggestions:Channel[]=[];
 const addSuggestion=(c:Channel|undefined)=>{if(c&&suggestions.length<4&&!suggestions.some(item=>item.id===c.id))suggestions.push(c);};
 for(const c of tv.catalog.channels){if(suggestions.length===4)break;if(!tv.isUnavailable(c)&&tv.lastSuccess(c)>Date.now()-24*3600_000)addSuggestion(c);}
 for(const id of featured)addSuggestion(tv.catalog.channels.find(c=>c.id===id));
 for(const c of tv.catalog.channels){if(suggestions.length===4)break;if(!tv.isUnavailable(c))addSuggestion(c);}
 const cctvNumber=selected.name.match(/^CCTV(\d+)(\+)?$/);const official=cctvNumber?`https://tv.cctv.com/live/cctv${cctvNumber[1]}${cctvNumber[2]?"plus":""}/`:undefined;
 return <><header className="topbar"><a className="brand" href="/" aria-label="SignalScout TV 首页"><img className="brand-mark" src="/favicon.svg" width={38} height={38} alt=""/>SignalScout <b>TV</b></a><span className="topnote"><Radio size={16}/> 你的频道，自动连接。</span></header>
 <div className="workspace"><aside className="channel-panel"><div className="panel-heading"><h2>频道库</h2><span className="small">{tv.catalog.channels.length?`${tv.catalog.channels.length} 个频道`:"等待目录"}</span></div><label className="search"><Search/><input type="search" aria-label="搜索频道" placeholder="搜索频道，如 CCTV5+" value={query} onChange={e=>setQuery(e.target.value)}/></label>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="catalog-tabs"><TabsTrigger value="all"><Tv/>全部</TabsTrigger><TabsTrigger value="favorites"><Star/>收藏</TabsTrigger><TabsTrigger value="recent"><History/>最近</TabsTrigger></TabsList></Tabs>
 <div className="category-row" aria-label="频道分类">{categories.map(c=><button key={c} className={tv.category===c&&tab==="all"?"active":""} onClick={()=>{tv.setCategory(c);setTab("all");setQuery("");}}>{c}</button>)}<button className={tab==="available"?"active":""} onClick={()=>{setTab("available");setQuery("");}}>本机可播</button><button className={tab==="shared"?"active":""} onClick={()=>{setTab("shared");setQuery("");}}>他人可播</button></div>
 <div className="hide-failed-filter"><label htmlFor="hide-failed">不显示失效源</label><Switch id="hide-failed" checked={tv.prefs.hideFailed} onCheckedChange={tv.setHideFailed}/></div><div className="channel-list">{channelPage.visible.map(c=><button aria-pressed={selected.id===c.id} className={`channel-item ${selected.id===c.id?"selected":""}`} onClick={()=>tv.selectChannel(c.id)} key={c.id}><span className="channel-detail"><strong>{channelDisplayName(c)}</strong><span>{channelStatus(c)}</span></span><span className={`channel-signal signal-${channelSignal(c)}`} role="img" aria-label={channelStatus(c)} title={channelStatus(c)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><g className="signal-bars"><path d="M4 19v-2"/><path d="M9 19v-6"/><path d="M14 19V9"/><path d="M19 19V5"/></g>{["unavailable","offline","restricted"].includes(channelSignal(c))&&<path d="M3 3l18 18"/>}{["pending","stale"].includes(channelSignal(c))&&<circle cx="19" cy="5" r="2.5" fill="var(--background)"/>}</svg></span></button>)}{channelPage.remaining>0&&<button className="quiet-button" onClick={()=>{setExpanded(true);setVisibleCount(channelPage.visible.length+80);}}>更多（还有 {channelPage.remaining} 个频道）</button>}{!filtered.length&&<Empty className="empty-message"><EmptyDescription>{!tv.catalog.channels.length?(tv.catalogLoading?"正在从 GitHub 加载目录…":"暂无频道目录，请刷新页面重试。"):query?"没有找到这个频道，试试其他名称。":tab==="favorites"?"还没有收藏。点亮频道旁的星星，即可留在这里。":tab==="recent"?"成功播放的频道会显示在这里。":tab==="available"?"还没有本机验证记录。选择一个频道，系统会自动尝试。":tab==="shared"?"暂时没有共享可播记录。":"暂时没有可用频道，可搜索其他频道。"}</EmptyDescription></Empty>}</div></aside>
 <main className="main-surface"><div className="eyebrow">LIVE TELEVISION</div><div className="watch-heading"><h1>{channelDisplayName(selected)}<span>{selected.group}</span></h1><button disabled={!tv.ready||!selected.id} aria-pressed={starred} onClick={tv.toggleFavorite} className={`quiet-button ${starred?"saved":""}`}><Star fill={starred?"currentColor":"none"}/>{starred?"已收藏":"收藏频道"}</button></div>
 {tv.notice&&!catalogNotice&&<p className="notice" role="status">{tv.notice}</p>}
 <div className="watch-grid"><div><div className="video-frame"><video ref={tv.video} playsInline controls={hasVideo} aria-label={`${selected.name} 直播播放器`} onVolumeChange={()=>setMuted(tv.video.current?.muted??true)}/>{!hasVideo&&<><span className="video-tag">{selected.name}</span><div className="video-idle">{busy?<LoaderCircle className="screen-icon spin"/>:state==="offline"?<WifiOff className="screen-icon"/>:<Tv className="screen-icon"/>}<h2>{!selected.id?(tv.catalogLoading?"正在加载频道目录…":"频道目录尚未加载"):statusText[state]}</h2><p>{!selected.id?"从 GitHub 获取最新频道，随后自动验证播放。":state==="unavailable"?tv.playback.reason:state==="offline"?"网络恢复后会继续连接。":state==="blocked"?"浏览器需要你点击一次，才能开始播放。":state==="stopped"?tv.playback.reason:"正在当前设备寻找可播放的连接"}</p>{state==="blocked"?<button className="primary-button" onClick={tv.resume}><Play/>点击播放</button>:state==="unavailable"&&official?<a className="primary-button" href={official} target="_blank" rel="noreferrer">前往央视官方观看<ArrowUpRight/></a>:state==="stopped"?<button className="primary-button" onClick={tv.retry}><Play/>重新连接</button>:null}</div></>}{hasVideo&&state==="blocked"&&<div className="video-idle"><button className="primary-button" onClick={tv.resume}><Play/>继续播放</button></div>}</div>
 <div className="under-player"><span className={`play-state ${playing?"state-playing":""}`} aria-live="polite">{busy?<LoaderCircle className="spin"/>:<Radio/>}{state==="unavailable"&&!browserSources(selected).length?"网页直连受限":statusText[state]}{playing?(tv.playback.streamType==="live"?" · 直播流":" · 直播待确认"):""} {tv.playback.resolution&&`· ${tv.playback.resolution}`}</span>{playing&&muted?<button className="sound-button" onClick={tv.unmute}><Volume2 size={16}/>开启声音</button>:<span>在当前设备验证播放</span>}</div>{selected.id&&<SourceList key={selected.id} device={tv.device} deviceHealth={tv.deviceHealth} channel={selected} checks={tv.sourceChecks} shared={tv.sharedHealth} hideFailed={tv.prefs.hideFailed} activeSource={tv.playback.source||tv.playback.attemptSource} onSelect={tv.selectSource} onRecheck={tv.recheckSources}/>}</div>
 <aside><div className="connection-card"><div className="card-overline"><Signal/> SMART CONNECT</div><h2>{playing?"安心看，自动续连":state==="unavailable"?"等待新的连接":"连接交给我们"}</h2><p>{playing?tv.backupCount>0?`${tv.backupCount} 条备用线路近期验证可播。`:"已找到可播线路，当前设备持续确认播放。":state==="unavailable"?"目录更新或冷却结束后，自动重新尝试。":"优先使用上次成功的线路，播放中断时自动恢复。"}</p><div className="connection-rule"/><div className="switch-row"><label htmlFor="auto-switch">中断时自动换源</label><Switch id="auto-switch" checked={tv.prefs.autoSwitch} onCheckedChange={tv.setAuto}/></div><button className="quiet-button" onClick={tv.retry} disabled={!tv.ready||!selected.id||busy||state==="offline"}><RefreshCw/>重新连接</button></div><div className="private-note"><ShieldCheck/><span>收藏与观看记录仅保存在此浏览器。</span></div><section className="explore-section"><div className="section-title"><h2>换个频道看看</h2><span className="small">自动为你连接</span></div><div className="channel-cards">{suggestions.map(c=><button key={c.id} onClick={()=>tv.selectChannel(c.id)} className={`channel-card ${c.id===selected.id?"active":""}`}><div className="tile-top"><strong>{channelDisplayName(c)}</strong><ArrowUpRight/></div><div className="tile-bottom"><span>{c.group}</span><small>{channelStatus(c)}</small></div></button>)}</div></section></aside></div>
 <footer className="footnote"><div className="catalog-summary"><span title={tv.catalog.syncedAt?new Date(tv.catalog.syncedAt).toLocaleString("zh-CN",{hour12:false}):undefined}>{tv.catalog.syncedAt?`同步于 ${new Date(tv.catalog.syncedAt).toLocaleTimeString("zh-CN",{hour12:false})}`:"尚未同步"}</span><span>不录制、不保存视频</span>{tv.syncMessage&&<span className="sync-message" role="status">{tv.syncMessage}</span>}</div>{showCatalogRefresh&&<div className="catalog-actions"><button className="quiet-button" onClick={()=>void tv.refresh()} disabled={tv.catalogLoading}><RefreshCw className={tv.catalogLoading?"spin":""}/>{tv.catalogLoading?"正在更新…":"更新目录"}</button></div>}{catalogNotice&&<p className="catalog-notice" role="status">{catalogNotice}</p>}</footer></main></div></>;
}
